/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("HeaderObjectPageObjectPage journey");

        opaTest("Navigate to HeaderObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheHeaderListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheHeaderListGenerated.onTable().iCheckRows();
            When.onTheHeaderListGenerated.onTable().iPressRow(0);

            Then.onTheHeaderObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the number of sections of the Object Page", function (_Given, _When, Then) {
            Then.onTheHeaderObjectPageGenerated.iCheckNumberOfSections(2);
        });

        opaTest("Check the Main section of the Object Page", function (_Given, When, Then) {
            When.onTheHeaderObjectPageGenerated.iGoToSection({ section: "Main" });
            Then.onTheHeaderObjectPageGenerated.iCheckSection({ section: "Main" });
            Then.onTheHeaderObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "headerID" });
            Then.onTheHeaderObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "email" });
            Then.onTheHeaderObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "firstName" });
            Then.onTheHeaderObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "lastName" });
            Then.onTheHeaderObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "country_code" });
            Then.onTheHeaderObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "createOn" });
            Then.onTheHeaderObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "deliveryDate" });
            Then.onTheHeaderObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "orderStatus_code" });
            Then.onTheHeaderObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "imageUrl" });
        });

        opaTest("Check the SalesOrderItems section of the Object Page", function (_Given, When, Then) {
            When.onTheHeaderObjectPageGenerated.iGoToSection({ section: "SalesOrderItems" });
            Then.onTheHeaderObjectPageGenerated.iCheckSection({ section: "SalesOrderItems" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});