/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ItemObjectPageObjectPage journey");

        opaTest("Navigate to ItemObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheHeaderListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheHeaderListGenerated.onTable().iCheckRows();
            When.onTheHeaderListGenerated.onTable().iPressRow(0);

            Then.onTheHeaderObjectPageGenerated.iSeeThisPage();
            Then.onTheHeaderObjectPageGenerated.onTable({ property: "items" }).iCheckRows();
            When.onTheHeaderObjectPageGenerated.onTable({ property: "items" }).iPressRow(0);

            Then.onTheItemObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the Main section of the Object Page", function (_Given, _When, Then) {
            Then.onTheItemObjectPageGenerated.iCheckSection({ section: "Main" });
            Then.onTheItemObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "itemID" });
            Then.onTheItemObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "name" });
            Then.onTheItemObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "description" });
            Then.onTheItemObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "releaseDate" });
            Then.onTheItemObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "discontinuedDate" });
            Then.onTheItemObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "price" });
            Then.onTheItemObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "height" });
            Then.onTheItemObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "width" });
            Then.onTheItemObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "depth" });
            Then.onTheItemObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "quantity" });
            Then.onTheItemObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "unitOfMeasure_code" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});